CREATE TABLE "INITIAL_WORKSHOP"."CLIENT" 
(	
    "CLIENT_ID" NUMBER GENERATED ALWAYS AS IDENTITY MINVALUE 1 MAXVALUE 9999999999999999999999999999 INCREMENT BY 1 START WITH 1 CACHE 20 NOORDER  NOCYCLE  NOKEEP  NOSCALE  NOT NULL ENABLE, 
    "CLIENT_ACTIVE" NUMBER, 
    "CLIENT_ADDRESS" VARCHAR2(255) NOT NULL ENABLE, 
    "CLIENT_DOCUMENT" NUMBER NOT NULL ENABLE, 
    "CLIENT_EMAIL" VARCHAR2(255) NOT NULL ENABLE, 
    "CLIENT_LASTNAME" VARCHAR2(255) NOT NULL ENABLE, 
    "CLIENT_NAME" VARCHAR2(255) NOT NULL ENABLE, 
    "CLIENT_PASSWORD" VARCHAR2(255) NOT NULL ENABLE, 
    "CLIENT_PHONE" VARCHAR2(255) NOT NULL ENABLE, 
    "CLIENT_SEX" VARCHAR2(255), 
    CONSTRAINT "IW_CLIENT_ID_PK" PRIMARY KEY ("CLIENT_ID")
        USING INDEX ENABLE, 
    CONSTRAINT "IW_CLIENT_DOCUMENT_ID_UK" UNIQUE ("CLIENT_DOCUMENT")
        USING INDEX ENABLE
);
/
CREATE TABLE "INITIAL_WORKSHOP"."ACCOUNT_TYPE"
(
	"ACCOUNT_TYPE_ID" NUMBER GENERATED ALWAYS AS IDENTITY MINVALUE 1 MAXVALUE 9999999999999999999999999999 INCREMENT BY 1 START WITH 1 CACHE 20 NOORDER  NOCYCLE  NOKEEP  NOSCALE  NOT NULL ENABLE, 
	"ACCOUNT_TYPE_NAME" VARCHAR(255) NOT NULL ENABLE, 
    
	CONSTRAINT "IW_ACCOUNT_TYPE_ID_PK" PRIMARY KEY("ACCOUNT_TYPE_ID")
		USING INDEX ENABLE,
        
    CONSTRAINT "IW_ACCOUNT_TYPE_NAME_UK" UNIQUE ("ACCOUNT_TYPE_NAME")
        USING INDEX ENABLE
)
/
CREATE TABLE "INITIAL_WORKSHOP"."ACCOUNT" 
(	
    "ACCOUNT_ID" NUMBER GENERATED ALWAYS AS IDENTITY MINVALUE 1 MAXVALUE 9999999999999999999999999999 INCREMENT BY 1 START WITH 1 CACHE 20 NOORDER  NOCYCLE  NOKEEP  NOSCALE  NOT NULL ENABLE, 
    "ACCOUNT_TYPE_ID" NUMBER NOT NULL ENABLE,
    "ACCOUNT_CLIENT_ID" NUMBER NOT NULL ENABLE, 
	"ACCOUNT_BALANCE" FLOAT NOT NULL ENABLE, 
    "ACCOUNT_COMP_RATE" FLOAT NOT NULL ENABLE, 
    "ACCOUNT_INTEREST_BALANCE" FLOAT NOT NULL ENABLE, 
    "ACCOUNT_OPENING_DATE" TIMESTAMP NOT NULL ENABLE, 
 
    CONSTRAINT "IW_ACCOUNT_ID_PK" PRIMARY KEY ("ACCOUNT_ID")
        USING INDEX ENABLE, 

    CONSTRAINT "IW_ACCOUNT_CLIENT_ID_FK" FOREIGN KEY ("ACCOUNT_CLIENT_ID")
        REFERENCES "INITIAL_WORKSHOP"."CLIENT" ("CLIENT_ID") ENABLE,
        
	CONSTRAINT "IW_ACCOUNT_TYPE_ID_FK" FOREIGN KEY ("ACCOUNT_TYPE_ID")
        REFERENCES "INITIAL_WORKSHOP"."ACCOUNT_TYPE" ("ACCOUNT_TYPE_ID") ENABLE
);
/
CREATE TABLE "INITIAL_WORKSHOP"."BRANCH" 
(
	"BRANCH_ID" NUMBER GENERATED ALWAYS AS IDENTITY MINVALUE 1 MAXVALUE 9999999999999999999999999999 INCREMENT BY 1 START WITH 1 CACHE 20 NOORDER  NOCYCLE  NOKEEP  NOSCALE  NOT NULL ENABLE, 
	"BRANCH_NAME" VARCHAR2(255),
	"BRANCH_CITY" VARCHAR2(255),
	"BRANCH_ADDRESS" VARCHAR2(255),
	"BRANCH_OPEN_TIME" VARCHAR2(255),
	"BRANCH_CLOSE_TIME" VARCHAR2(255),
     
    CONSTRAINT "IW_BRANCH_ID_PK" PRIMARY KEY ("BRANCH_ID")
        USING INDEX ENABLE 
);
/
CREATE TABLE "INITIAL_WORKSHOP"."TRANSACTION_TYPE"
(
    "TRANSACTION_TYPE_ID" NUMBER GENERATED ALWAYS AS IDENTITY MINVALUE 1 MAXVALUE 9999999999999999999999999999 INCREMENT BY 1 START WITH 1 CACHE 20 NOORDER  NOCYCLE  NOKEEP  NOSCALE  NOT NULL ENABLE, 
    "TRANSACTION_TYPE_NAME" VARCHAR2(255),

    CONSTRAINT "IW_TRANSACTION_TYPE_ID_PK" PRIMARY KEY ("TRANSACTION_TYPE_ID")
        USING INDEX ENABLE, 
        
    CONSTRAINT "IW_TRANSACTION_TYPE_NAME_UK" UNIQUE ("TRANSACTION_TYPE_NAME")
        USING INDEX ENABLE
);
/
CREATE TABLE "INITIAL_WORKSHOP"."TRANSACTION"
(
    "TRANSACTION_ID" NUMBER GENERATED ALWAYS AS IDENTITY MINVALUE 1 MAXVALUE 9999999999999999999999999999 INCREMENT BY 1 START WITH 1 CACHE 20 NOORDER  NOCYCLE  NOKEEP  NOSCALE  NOT NULL ENABLE, 
    "TRANSACTION_BRANCH_ID" NUMBER NOT NULL ENABLE,
    "TRANSACTION_TYPE_ID" NUMBER NOT NULL ENABLE,
    "TRANSACTION_ORIGIN_ACCOUNT_ID" NUMBER,
    "TRANSACTION_DEST_ACCOUNT_ID" NUMBER,
    "TRANSACTION_VALUE" FLOAT,
    "TRANSACTION_STATE" NUMBER NOT NULL ENABLE,

    CONSTRAINT "IW_TRANSACTION_ID_PK" PRIMARY KEY ("TRANSACTION_ID")
        USING INDEX ENABLE, 

    CONSTRAINT "IW_TRANSACTION_BRANCH_ID_FK" FOREIGN KEY ("TRANSACTION_BRANCH_ID")
        REFERENCES "INITIAL_WORKSHOP"."BRANCH" ("BRANCH_ID") ENABLE,

    CONSTRAINT "IW_TRANSACTION_TYPE_ID_FK" FOREIGN KEY ("TRANSACTION_TYPE_ID")
        REFERENCES "INITIAL_WORKSHOP"."TRANSACTION_TYPE" ("TRANSACTION_TYPE_ID") ENABLE,  

    CONSTRAINT "IW_TRANSACTION_ORIGIN_ACCOUNT_ID_FK" FOREIGN KEY ("TRANSACTION_ORIGIN_ACCOUNT_ID")
        REFERENCES "INITIAL_WORKSHOP"."ACCOUNT" ("ACCOUNT_ID") ENABLE,

    CONSTRAINT "IW_TRANSACTION_DEST_ACCOUNT_ID_FK" FOREIGN KEY ("TRANSACTION_DEST_ACCOUNT_ID")
        REFERENCES "INITIAL_WORKSHOP"."ACCOUNT" ("ACCOUNT_ID") ENABLE
);



